#!/usr/bin/env Rscript
library(data.table)
library(tidyr)
args = commandArgs(trailingOnly=TRUE)
print(args[1])
indels = FALSE
if (length(grep("indel",args[1]))==1) {
    indels = TRUE
    print("indels file")
}else{
    print("snvs file")
}

#get allelicfraction
#snvs<-read.table(args[1], sep="\t", header=T)
snvs<-fread(paste0("zcat ", args[1]), skip = "CHROM")
dict<-list( "A"=5, "C"=6, "G"=7, "T"=8 )

#filter PASS
snvs<-snvs[snvs$FILTER=="PASS",]


#get REF column and get only first letter if needed
ref<-as.factor(snvs$REF)
if (length(levels(ref))>4){
    alt<-unlist(lapply(as.character(snvs$REF), function(x){ strsplit( x, ",")[[1]][1] } ))
}


#get ALT column and get only first letter if needed
alt<-as.factor(snvs$ALT)
if (length(levels(alt))>4){
    alt<-unlist(lapply(as.character(snvs$ALT), function(x){ strsplit( x, ",")[[1]][1] } ))
}

#split NORMAL column by ","
n<-strsplit(as.character(snvs$NORMAL),":")

#split TUMOR column by ","
t<-strsplit(as.character(snvs$TUMOR),":")

Cov_N<-Cov_T<-AF_N<-AF_T<-0

if (!indels){

    #get coverage in normal
    Cov_N<-as.numeric(unlist(lapply( n, function(x){ x[1] } )))
    filtered<-as.numeric(unlist(lapply( n, function(x){ x[2] } )))
    Cov_N<-Cov_N-filtered

    #get allelic fraction
    AF_N<-unlist(lapply( 1:length(alt), function(x){
        if (alt[x]==".") {0} else { as.numeric(strsplit( n[[x]][ dict[[alt[x]]] ],",")[[1]][1]) }
    }))
    AF_N<-AF_N/Cov_N

    #get coverage in tumor
    Cov_T<-as.numeric(unlist(lapply( t, function(x){ x[1] } )))
    filtered<-as.numeric(unlist(lapply( t, function(x){ x[2] } )))
    Cov_T<-Cov_T-filtered

    #get allelic fraction
    AF_T<-unlist(lapply( 1:length(alt), function(x){
        if (alt[x]==".") {0} else { as.numeric(strsplit( t[[x]][ dict[[alt[x]]] ],",")[[1]][1]) }
    }))
    AF_T<-AF_T/Cov_T
}

if (indels){

    #get coverage in normal
    Cov_N<-as.numeric(unlist(lapply( n, function(x){ x[1] } )))
    #get allelic fraction
    AF_N<-unlist(lapply( 1:length(ref), function(x){
        as.numeric(strsplit( n[[x]][ 4 ],",")[[1]][1])
    }))
    AF_N<-AF_N/Cov_N

    #get coverage in tumor
    Cov_T<-as.numeric(unlist(lapply( t, function(x){ x[1] } )))
    #get allelic fraction
    AF_T<-unlist(lapply( 1:length(alt), function(x){
        as.numeric(strsplit( t[[x]][ 4 ],",")[[1]][1])
    }))
    AF_T<-AF_T/Cov_T
}


nh<-sapply( strsplit(snvs$FORMAT[1],":"), function(x){ paste0("N_",x)} )
nt<-sapply( strsplit(snvs$FORMAT[1],":"), function(x){ paste0("T_",x)} )
foo<-cbind(snvs[,1:5], Cov_N, Cov_T, AF_N, AF_T, snvs[,6:ncol(snvs)])
foo<-separate(foo,col = "NORMAL",into = nh, sep = ":")
foo<-separate(foo,col = "TUMOR",into = nt, sep = ":")
write.table(foo, file=paste0( substr( args[1], 1, nchar(args[1])-6), "vcf"), sep="\t", row.names=F, quote=F)


